### ISSUE TITLE
 added to the $PATH

### ISSUE THREAD

**Issue by JNDX1** [jjvanantwerp/Automated-ASR#1]
Hello, README said be sure that CD-Hit, MAFFT, and IQ-Tree are installed, and their executables have been added to the $PATH such that the executable lines will run.I run Automated using PyCharm software on my Windows system. How do I add the $PATH for the software?

**Comment by jjvanantwerp** [comment]
Hi, thank you for your interest! I am afraid that I am not familiar with the PyCharm environment. When I say that executables must be added to the $PATH, that is a variable of Linux systems, where I run AutoASR. On a windows device, you should change all the executable lines so that the executable command is what you would use to run CDHit or MAFFT from the terminal/command line. The executable lines are those lines in the python file beginning with "os.system(..."
I hope this is helpful, and please reach out with any other questions you have!
________________________________
From: JNDX1 ***@***.***>
Sent: Tuesday, October 4, 2022 11:44 AM
To: jjvanantwerp/Automated-ASR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jjvanantwerp/Automated-ASR] added to the $PATH (Issue #1)


Hello, README said be sure that CD-Hit, MAFFT, and IQ-Tree are installed, and their executables have been added to the $PATH such that the executable lines will run.I run Automated using PyCharm software on my Windows system. How do I add the $PATH for the software?

**Comment by JNDX1** [comment]
你好，我已经收到邮件。
